### ISSUE TITLE
[iOS] Module 'AudioKit' has no member named 'output', 'start'

### ISSUE THREAD

**Issue by Ro4z** [FYLSunghwan/react-native-piano-sampler#4]
I got this error when build on iPhone XS simulator(iOS 13.7). I clearly fulfilled all prerequisites😞
<img width="669" alt="스크린샷 2020-10-06 오전 11 02 53" src="https://user-images.githubusercontent.com/52953420/95156137-c6830780-07d0-11eb-935a-6158a506ea0d.png">

**Comment by martonszabolcs** [comment]
Hi there,

The problem is the updated AudioKit/Core
Please use 4. version like this:
`  pod 'AudioKit/Core', '4.11.2'` - in your app's podfile
